In [1]:
import numpy as np

In [2]:
x =[[1,2],[3,4]]
total = 0
for i in x:
    total += sum(i)
print(total)

10


In [4]:
x = [[1,2],[3,4]]
nx = np.array(x)

In [5]:
print(nx.sum())
print(nx.min())
print(nx.max())
print(nx.std())
print(nx.var())
print(nx.mean())

10
1
4
1.118033988749895
1.25
2.5


In [6]:
type(nx)

numpy.ndarray

In [7]:
print(nx.shape)  # shape of matrix
print(nx.size)  # total elements
print(nx.dtype) # type of elements

(2, 2)
4
int64


In [8]:
y = [[1,2,3],[4,5,6],[7,8,9]]

functions to create matrix

- `arange`: create a range of numbers
- `linspace`: create a matrix of specified number of elements
- `ones`: create a matrix of ones
- `zeros`: create a matrix of zeros
- `random.rand`: create a matrix of random floats
- `random.randint`: create a matrix of random integers
- `diag`: create a matrix of diagonal elements

In [9]:
a = np.arange(1,50)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [10]:
np.arange(1, 3, .2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [11]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.zeros((1,3), dtype=int)

array([[0, 0, 0]])

In [18]:
np.random.randint(1,100,10)

array([64, 26, 18, 32, 82, 26, 13, 55, 98, 65], dtype=int32)

In [19]:
np.random.randint(-4,7,(4,3))

array([[ 1, -4,  4],
       [-1, -3, -3],
       [ 2, -3,  6],
       [ 1,  4,  5]], dtype=int32)

In [20]:
np.random.randint(-4,7,(4,3,2))

array([[[ 1,  6],
        [-2,  5],
        [ 0, -1]],

       [[ 1, -4],
        [ 2,  1],
        [-1,  2]],

       [[ 1,  4],
        [-2, -2],
        [-2,  4]],

       [[-1, -1],
        [-1,  3],
        [ 4, -1]]], dtype=int32)

In [21]:
np.random.rand(5)

array([0.72150181, 0.54321623, 0.40687016, 0.32761155, 0.34548378])

In [22]:
np.random.rand(10,5)

array([[0.26393637, 0.72372061, 0.70650297, 0.41231441, 0.27123044],
       [0.09603247, 0.27249451, 0.36623544, 0.85658376, 0.19423481],
       [0.25957975, 0.72266525, 0.04155801, 0.92959729, 0.28476185],
       [0.60594582, 0.32298932, 0.94202775, 0.91809873, 0.36457101],
       [0.39845987, 0.88941696, 0.97089437, 0.37338265, 0.824535  ],
       [0.19078311, 0.40963742, 0.68161195, 0.89674327, 0.27671826],
       [0.05834886, 0.93377968, 0.07171894, 0.13409586, 0.70694776],
       [0.92173842, 0.97656713, 0.37654139, 0.46159438, 0.79343591],
       [0.19742043, 0.64640276, 0.51574048, 0.4740094 , 0.50911206],
       [0.04067375, 0.93664756, 0.68166158, 0.12674064, 0.06231144]])

In [23]:
np.set_printoptions(precision=3)
np.random.rand(10,5)

array([[0.176, 0.417, 0.552, 0.132, 0.522],
       [0.355, 0.885, 0.479, 0.78 , 0.128],
       [0.452, 0.817, 0.864, 0.751, 0.446],
       [0.413, 0.6  , 0.252, 0.152, 0.814],
       [0.866, 0.23 , 0.526, 0.44 , 0.421],
       [0.401, 0.358, 0.305, 0.004, 0.671],
       [0.198, 0.986, 0.769, 0.367, 0.674],
       [0.056, 0.323, 0.529, 0.208, 0.16 ],
       [0.967, 0.915, 0.464, 0.189, 0.343],
       [0.814, 0.33 , 0.22 , 0.2  , 0.469]])

In [24]:
x =[1,2,3,4,5]
np.diag(x)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [25]:
#reshape
np.arange(10).reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
x= np.linspace(1, 5, 25).reshape(5,5)

In [27]:
x.flatten()

array([1.   , 1.167, 1.333, 1.5  , 1.667, 1.833, 2.   , 2.167, 2.333,
       2.5  , 2.667, 2.833, 3.   , 3.167, 3.333, 3.5  , 3.667, 3.833,
       4.   , 4.167, 4.333, 4.5  , 4.667, 4.833, 5.   ])

In [28]:
y = np.arange(1, 26).reshape(5,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [29]:
y.transpose()

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [31]:
y.T    # shortcut for above

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

MATHS

In [32]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)

[[6 8 3]
 [3 4 5]
 [4 3 3]]
[[5 5 6]
 [4 6 9]
 [6 4 8]]


In [33]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[11 13  9]
 [ 7 10 14]
 [10  7 11]]
[[ 1  3 -3]
 [-1 -2 -4]
 [-2 -1 -5]]
[[30 40 18]
 [12 24 45]
 [24 12 24]]
[[1.2   1.6   0.5  ]
 [0.75  0.667 0.556]
 [0.667 0.75  0.375]]


In [34]:
a.dot(b)  # dot product

array([[ 80,  90, 132],
       [ 61,  59,  94],
       [ 50,  50,  75]], dtype=int32)

In [35]:
a+10

array([[16, 18, 13],
       [13, 14, 15],
       [14, 13, 13]], dtype=int32)

STATS

In [36]:
print(a.mean())

4.333333333333333


In [37]:
print(a.mean())
print(a.mean(axis=0)) # column wise
print(a.mean(axis=1)) # row wise

4.333333333333333
[4.333 5.    3.667]
[5.667 4.    3.333]


In [38]:
np.sin(a)

array([[-0.279,  0.989,  0.141],
       [ 0.141, -0.757, -0.959],
       [-0.757,  0.141,  0.141]])

In [39]:
x = np.random.randint(1, 100, (2,5))
print(x)

[[22 64 83 33 48]
 [17 41 53 75 78]]


In [40]:
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())

83
2
17
5


Slicing
- 1D - [start : stop : step]
- 2D - [row_start : row_stop : row_step , col_start : col_stop : col_step]

In [41]:
x= np.arange(1,11)
print(x[:5])
print(x[-5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [42]:
x= np.linspace(1, 100, 25).reshape(5,5).astype(int)
print(x)
print(x[0])    # row index 0
print(x[-1])   # last row 
print(x[2])    # # row index2
print(x[:3])  # row index 0 to 2
print(x[-2])  #  last 2 rows

print(x[:0]) # coulmn index 0
print(x[:,-1]) # last coulmn

[[  1   5   9  13  17]
 [ 21  25  29  34  38]
 [ 42  46  50  54  58]
 [ 62  67  71  75  79]
 [ 83  87  91  95 100]]
[ 1  5  9 13 17]
[ 83  87  91  95 100]
[42 46 50 54 58]
[[ 1  5  9 13 17]
 [21 25 29 34 38]
 [42 46 50 54 58]]
[62 67 71 75 79]
[]
[ 17  38  58  79 100]


In [43]:
x>50   # boolean filter

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [44]:
x[x>50]   # broadcasting

array([ 54,  58,  62,  67,  71,  75,  79,  83,  87,  91,  95, 100])

In [45]:
x[(x>40) & (x<80)]

array([42, 46, 50, 54, 58, 62, 67, 71, 75, 79])

In [46]:
x[x % 2 == 0]

array([ 34,  38,  42,  46,  50,  54,  58,  62, 100])

3rd party libraries

- `plotly` - interactive plot using html

- `matplotlib` - ploting library for almost all types of plots(image)

- `seaborn` - plotting library for statistical plots(extension of mat)

- `scipy` - for support in seaborn

- `nbformat` - for support in plotly

- `statsmodels` - for support in seaborn